# Generated by Django 4.2.3 on 2023-12-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('shared_post', 'liked_user'), name='unique_shared_post_like'),
        ),
    ]
