# Generated by Django 5.0 on 2023-12-24 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_like_unique_shared_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_shared_post', to='post.sharedpost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='post.post'),
        ),
    ]
